# Generated by Django 4.1.3 on 2023-01-03 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Asec", "0013_announcements_delete_announcemnets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="committeeId",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="Asec.committee",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="roleId",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="Asec.role"
            ),
        ),
    ]
