# Generated by Django 4.1.4 on 2022-12-17 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asec', '0002_commitee_role_tracker'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commitee',
            new_name='Committee_des',
        ),
    ]
