# Generated by Django 4.1.3 on 2022-12-27 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asec', '0006_remove_role_urlid_role_urlid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Committee_des',
        ),
        migrations.AlterField(
            model_name='committee',
            name='headId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='urls',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='committeeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asec.committee'),
        ),
        migrations.AlterField(
            model_name='user',
            name='roleId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asec.role'),
        ),
    ]
