# Generated by Django 4.1.4 on 2022-12-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asec', '0007_delete_committee_des_alter_committee_headid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='announcemnets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
