# Generated by Django 4.1.4 on 2022-12-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asec', '0008_announcemnets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcemnets',
            name='description',
            field=models.TextField(),
        ),
    ]
