# Generated by Django 4.1.3 on 2022-12-30 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asec', '0009_alter_announcemnets_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='attendance',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tracker',
            name='member',
            field=models.ForeignKey(default='-1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tracker',
            name='task',
            field=models.CharField(default='No task yet', max_length=255),
        ),
        migrations.AlterField(
            model_name='announcemnets',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
