# Generated by Django 4.1.3 on 2022-12-30 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asec', '0010_tracker_attendance_tracker_member_tracker_task_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='member',
        ),
        migrations.AddField(
            model_name='tracker',
            name='assigned_by',
            field=models.ForeignKey(default='-1', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tracker',
            name='assigned_to',
            field=models.ForeignKey(default='-1', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
