# Generated by Django 4.1.3 on 2022-12-31 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asec', '0011_remove_tracker_member_tracker_assigned_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='tracker',
            name='description',
            field=models.CharField(default='Without description', max_length=255),
        ),
        migrations.AddField(
            model_name='tracker',
            name='user',
            field=models.ForeignKey(default='-1', on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to=settings.AUTH_USER_MODEL),
        ),
    ]
