# Generated by Django 4.1.3 on 2022-12-31 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asec', '0012_remove_tracker_assigned_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('facebookLink', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='announcemnets',
        ),
    ]
